## Rotation matrix

4 rotation functions: 
- rot(v1,v2)  --> better for beam rotation but slower ($\sim 85 \mu s$)  
- rot(R1, v2) + optimized version  --> use opt version for full convolution ($\sim 5 \mu s$)

Verified that they differ by numerical errors of $10^{-17}$

In [13]:
#%matplotlib widget
import numpy as np
import healpy as hp
import matplotlib.pyplot as plt
import timeit
import importlib

import functions_rot as frot

In [12]:
importlib.reload(frot)

<module 'functions_rot' from '/home/evanetti/BEAMS/beams_code/functions_rot.py'>

In [3]:
## Set: initial and final point of the rotation  
phi1, theta1 = 30., 45.
phi2, theta2 = 15., 60.
vc1=hp.pixelfunc.ang2vec(phi1, theta1, lonlat=True)
vc2=hp.pixelfunc.ang2vec(phi2, theta2, lonlat=True)
print('vc1 = ', vc1 )
print('vc2 = ', vc2 )

vc1 =  [0.61237244 0.35355339 0.70710678]
vc2 =  [0.48296291 0.12940952 0.8660254 ]


In [4]:
# Rotation matrix from initial and final position
Rot_matrix=frot.rotmatrix_frame_vec(vc1, vc2)  
print(Rot_matrix)

[[ 0.93742222  0.24236248 -0.25      ]
 [-0.26645656  0.9615163  -0.0669873 ]
 [ 0.22414387  0.12940952  0.96592583]]


In [5]:
# Rotation matrix to final position (build rotation to initial position in advance)
R1=frot.get_R1(vc1)
Rot_matrix=frot.rotmatrix_frame(R1, vc2)
print(Rot_matrix)

[[ 0.93742222  0.24236248 -0.25      ]
 [-0.26645656  0.9615163  -0.0669873 ]
 [ 0.22414387  0.12940952  0.96592583]]


In [6]:
# Rotation matrix to final position - same but optimized for final run
R1=frot.get_R1(vc1)
Rot_matrix=frot.rotmatrix_frame_opt(R1, vc2)
print(Rot_matrix)

[[ 0.93742222  0.24236248 -0.25      ]
 [-0.26645656  0.9615163  -0.0669873 ]
 [ 0.22414387  0.12940952  0.96592583]]


In [7]:
print('Vec rotation - optimized R1 rot\n', frot.rotmatrix_frame_vec(vc1, vc2)-frot.rotmatrix_frame_opt(R1, vc2), '\n' )
print('Vec rotation - R1 rot\n', frot.rotmatrix_frame_vec(vc1, vc2)-frot.rotmatrix_frame(R1, vc2), '\n'  )
print('oprimized R1 rot - R1 rot \n', frot.rotmatrix_frame_opt(R1, vc2)-frot.rotmatrix_frame(R1, vc2) )

Vec rotation - optimized R1 rot
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

Vec rotation - R1 rot
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

oprimized R1 rot - R1 rot 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Timing 

In [8]:
%timeit R_test=frot.rotmatrix_frame_vec(vc1, vc2)

286 μs ± 81.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%timeit R_test=frot.rotmatrix_frame(R1, vc2)

162 μs ± 35.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
%timeit R_test=frot.rotmatrix_frame_opt(R1, vc2)

32.4 μs ± 7.71 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
